version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deploy:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm deploy


workflows:
    build:
      jobs:
        - build
        - deploy:
            type: approval
            requires:
              - build
            filters:
              branches:
                only: master
