version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to GitHub pages
          command: npm run deploy

workflows:
    build:
      jobs:
        - build
#        - deploy:
#            type: approval
#            requires:
#              - build
            filters:
              branches:
                only: master
