# inspired by: https://joelhooks.com/jest-and-github-actions

name: test

on:
  push:
    branches: [ master, 'fix/build-artifact' ]
  pull_request:
    branches: [ master ]

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules_${{ hashFiles('package-lock.json') }}
        #key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node_modules-
    - run: npm ci

  unit-test:
    needs: prepare-environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Load node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules_${{ hashFiles('package-lock.json') }} 
    - run: npm test
    - name: Tests ✅
      if: ${{ success() }}
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "context": "tests",
          "state": "success",
          "description": "Tests passed",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }'
    - name: Tests 🚨
      if: ${{ failure() }}
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "context": "tests",
          "state": "failure",
          "description": "Tests failed",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }'

  build-artifact:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Build artifact
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Create env file
      run: |
        touch .env
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_ACCESS_KEY_SECRET=${{ secrets.AWS_ACCESS_KEY_SECRET }} >> .env
        echo AWS_REGION=${{ secrets.AWS_REGION }} >> .env
    - name: Install Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm ci
    - name: Build app
      run: npm run build:aws


